'use client'

import { useMemo, useState } from 'react'
import {
  AlertTriangle, ArrowUpRight, Bell, CalendarDays, Check, ChevronDown, CircleHelp, ClipboardCheck,
  CloudUpload, Filter, HardHat, LayoutDashboard, ListFilter, Map, Menu, MoreHorizontal, Search,
  Settings, ShieldAlert, SlidersHorizontal, UserRound, Users, X, ZoomIn, ZoomOut,
} from 'lucide-react'

type Violation = {
  id: string; title: string; area: string; status: string; severity: string; sla: string; reporter: string; initials: string; progress: number; icon: 'roof' | 'dust' | 'ppe' | 'docs' | 'road'; due: string; evidence: string
}

const violations: Violation[] = [
  { id: 'VIO-2408', title: 'Roof support spacing exceeds 1.2m limit', area: 'Active Panel 3 · Section B', status: 'Open', severity: 'Critical', sla: 'Overdue by 6h', reporter: 'Rakesh Singh', initials: 'RS', progress: 22, icon: 'roof', due: 'Overdue', evidence: 'Roof support survey' },
  { id: 'VIO-2407', title: 'Dust suppression inactive at coal transfer point', area: 'Coal Yard · Transfer 02', status: 'Acknowledged', severity: 'High', sla: '2h 18m remaining', reporter: 'Priya Das', initials: 'PD', progress: 38, icon: 'dust', due: 'Due soon', evidence: 'Dust suppression valve' },
  { id: 'VIO-2405', title: 'Contractor missing valid induction record', area: 'Workshop · Gate 1', status: 'In Progress', severity: 'High', sla: '5h 42m remaining', reporter: 'Amit Ghosh', initials: 'AG', progress: 64, icon: 'docs', due: 'Open', evidence: 'Contractor register' },
  { id: 'VIO-2403', title: 'Unsafe PPE observed near crusher line', area: 'Crusher · North platform', status: 'Open', severity: 'Medium', sla: '18h 04m remaining', reporter: 'Suman Oraon', initials: 'SO', progress: 8, icon: 'ppe', due: 'Open', evidence: 'PPE observation' },
  { id: 'VIO-2401', title: 'Obstruction narrowing haul-road clearance', area: 'Haul Road · Marker 7', status: 'Resolved', severity: 'Low', sla: 'Closed yesterday', reporter: 'Vikas Kumar', initials: 'VK', progress: 100, icon: 'road', due: 'Open', evidence: 'Haul-road clearance' },
]

const team = [
  ['Meera Joshi', 'MJ', '8', '2', '92%'], ['Sanjay Yadav', 'SY', '6', '1', '86%'], ['Nikhil Verma', 'NV', '4', '0', '100%'], ['Fatima Bibi', 'FB', '3', '1', '78%'],
]

function Brand() { return <div className="brand"><div className="brand-mark"><HardHat size={20} /></div><span>Mine<span>OS</span></span></div> }
function IconButton({ label, children, onClick }: { label: string; children: React.ReactNode; onClick?: () => void }) { return <button aria-label={label} title={label} onClick={onClick} className="icon-btn">{children}</button> }
function Avatar({ initials, tone = 'blue' }: { initials: string; tone?: string }) { return <span className={`avatar avatar-${tone}`}>{initials}</span> }
function SeverityIcon({ type }: { type: Violation['icon'] }) { const Icon = type === 'roof' ? ShieldAlert : type === 'dust' ? CloudUpload : type === 'ppe' ? HardHat : type === 'docs' ? ClipboardCheck : AlertTriangle; return <span className="category-icon"><Icon size={17} /></span> }

export default function Page() {
  const [tab, setTab] = useState('All'); const [mine, setMine] = useState('Jharia OCP-3'); const [date, setDate] = useState('Today, 05 Sep 2026');
  const [selected, setSelected] = useState<Violation | null>(null); const [reportOpen, setReportOpen] = useState(false); const [notifications, setNotifications] = useState(false); const [toast, setToast] = useState(''); const [teamFilter, setTeamFilter] = useState('Assigned'); const [sidebarOpen, setSidebarOpen] = useState(false);
  const filtered = useMemo(() => violations.filter(v => tab === 'All' || (tab === 'Open' ? v.status !== 'Resolved' : v.due === tab)), [tab]);
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2600) }

  return <div className="app-shell">
    <aside className={`sidebar ${sidebarOpen ? 'sidebar-open' : ''}`}><Brand /><nav><NavItem active icon={<LayoutDashboard />} label="Dashboard" /><NavItem icon={<ClipboardCheck />} label="Reports" /><NavItem icon={<ShieldAlert />} label="Violations" /><NavItem icon={<Check />} label="Corrective actions" /><NavItem icon={<Map />} label="Mine map" /><NavItem icon={<Users />} label="Team" /><NavItem icon={<ListFilter />} label="Audit log" /></nav><div className="sidebar-bottom"><NavItem icon={<Settings />} label="Settings" /></div></aside>
    <main className="main-content">
      <header className="topbar"><IconButton label="Open navigation" onClick={() => setSidebarOpen(!sidebarOpen)}><Menu /></IconButton><div className="greeting"><p>Good morning, Arjun</p><span>Manager workspace · Saturday, 05 September 2026</span></div><div className="top-actions"><label className="select-wrap"><Map size={16} /><select value={mine} onChange={e => setMine(e.target.value)}><option>Jharia OCP-3</option><option>Raniganj OCP-2</option></select><ChevronDown size={14} /></label><label className="select-wrap date-select"><CalendarDays size={16} /><select value={date} onChange={e => setDate(e.target.value)}><option>Today, 05 Sep 2026</option><option>Last 7 days</option><option>This month</option></select><ChevronDown size={14} /></label><IconButton label="Search"><Search /></IconButton><div className="notification-wrap"><IconButton label="Notifications" onClick={() => setNotifications(!notifications)}><Bell /><b>3</b></IconButton>{notifications && <div className="notification-pop"><strong>Notifications</strong><p>VIO-2408 has breached its SLA.</p><p>2 reports need acknowledgement.</p><button onClick={() => setNotifications(false)}>Mark all as read</button></div>}</div><button className="primary-btn" onClick={() => setReportOpen(true)}>+ Report violation</button></div></header>
      <div className="page-heading"><div><p className="eyebrow">MANAGER DASHBOARD</p><h1>Safety at a glance</h1></div><button className="quick-link" onClick={() => setReportOpen(true)}><span className="quick-dot">+</span> Quick field report <ArrowUpRight size={15} /></button></div>
      <section className="kpi-grid">{[['12', 'Open violations', '+3.2%', 'vs last week', 'up'], ['4', 'Overdue / Escalated', '+1', 'vs last week', 'warn'], ['3', 'Due within 24 hours', '-2', 'vs last week', 'down'], ['78%', 'SLA compliance', '+6.4%', 'vs last week', 'up']].map(([value, label, trend, sub, tone]) => <div className={`kpi-card ${tone}`} key={label}><div><span>{label}</span><strong>{value}</strong></div><div className="kpi-trend">{tone === 'warn' ? <AlertTriangle size={14} /> : <ArrowUpRight size={14} />} {trend} <small>{sub}</small></div></div>)}</section>
      <div className="content-grid"><section className="panel queue-panel"><div className="panel-header"><div><h2>Violation action queue</h2><p>Prioritized by risk and SLA deadline</p></div><div className="panel-tools"><IconButton label="Filter queue"><Filter /></IconButton><IconButton label="More options"><MoreHorizontal /></IconButton></div></div><div className="tabs">{['All', 'Open', 'Due soon', 'Overdue'].map(item => <button className={tab === item ? 'active' : ''} onClick={() => setTab(item)} key={item}>{item}<span>{item === 'All' ? 12 : item === 'Open' ? 8 : item === 'Due soon' ? 3 : 4}</span></button>)}</div><div className="queue-list">{filtered.map(v => <button className="violation-row" key={v.id} onClick={() => setSelected(v)}><SeverityIcon type={v.icon} /><div className="violation-copy"><div className="row-title"><strong>{v.title}</strong><span className={`status status-${v.status.toLowerCase().replace(' ', '-')}`}>{v.status}</span></div><span className="row-meta">{v.id} · {v.area}</span><div className="row-progress"><span><i style={{ width: `${v.progress}%` }} /></span><small>{v.progress}% actioned</small></div></div><div className={`sla ${v.sla.includes('Overdue') ? 'sla-overdue' : ''}`}><strong>{v.sla}</strong><span>{v.reporter} <Avatar initials={v.initials} /></span></div><div className="evidence-thumb"><span>{v.evidence}</span></div></button>)}</div><button className="view-all" onClick={() => notify('All violations loaded')}>View all violations <ArrowUpRight size={15} /></button></section>
        <aside className="right-stack"><section className="panel attention-panel"><div className="panel-header"><div><h2>Requires your attention</h2><p>3 items need a decision</p></div><span className="count-badge">3</span></div>{violations.slice(0, 3).map((v, i) => <div className="attention-item" key={v.id}><div className={`risk-dot risk-${i === 0 ? 'critical' : 'high'}`} /><div><strong>{v.title}</strong><p>{i === 0 ? 'Safety risk requires immediate isolation.' : 'Owner has not confirmed a corrective action.'}</p><span className={i === 0 ? 'overdue-text' : ''}>{i === 0 ? 'Overdue by 6h' : 'Due in 2h 18m'}</span></div><button onClick={() => setSelected(v)}>{i === 0 ? 'Review now' : 'Assign action'} <ArrowUpRight size={13} /></button></div>)}</section><section className="panel sla-panel"><div className="panel-header"><div><h2>SLA health</h2><p>Current violation workload</p></div><span className="sla-score">78%</span></div><div className="sla-body"><div className="donut"><span>15<br /><small>total</small></span></div><div className="legend"><span><i className="dot green" />On track <b>8</b></span><span><i className="dot amber" />Due soon <b>3</b></span><span><i className="dot red" />Escalated <b>4</b></span></div></div></section></aside>
        <section className="panel map-panel"><div className="panel-header"><div><h2>Mine activity &amp; risk</h2><p>Live report locations · {mine}</p></div><button className="text-btn" onClick={() => notify('Opening full mine map')}>View full mine map <ArrowUpRight size={15} /></button></div><div className="mine-map"><div className="map-controls"><IconButton label="Zoom in"><ZoomIn /></IconButton><IconButton label="Zoom out"><ZoomOut /></IconButton></div><div className="zone zone-panel"><span>Active Panel 3</span></div><div className="zone zone-haul"><span>Haul Road</span></div><div className="zone zone-workshop"><span>Workshop</span></div><div className="zone zone-coal"><span>Coal Yard</span></div><span className="map-marker marker-red" style={{ left: '32%', top: '34%' }} /><span className="map-marker marker-amber" style={{ left: '68%', top: '48%' }} /><span className="map-marker marker-blue" style={{ left: '48%', top: '72%' }} /><span className="map-marker marker-red" style={{ left: '76%', top: '77%' }} /><div className="map-legend"><span><i className="dot red" />Critical</span><span><i className="dot amber" />High</span><span><i className="dot blue" />Normal</span></div></div></section>
        <section className="panel team-panel"><div className="panel-header"><div><h2>Team corrective actions</h2><p>Ownership and completion performance</p></div><IconButton label="Team options"><MoreHorizontal /></IconButton></div><div className="team-toolbar"><label className="search-field"><Search size={15} /><input placeholder="Search team" /></label><div className="segmented">{['Assigned', 'Unassigned'].map(x => <button className={teamFilter === x ? 'active' : ''} onClick={() => setTeamFilter(x)} key={x}>{x}</button>)}</div></div><div className="team-table"><div className="team-head"><span>Team member</span><span>Active actions</span><span>Due today</span><span>Completion</span></div>{team.map(([name, initials, active, due, rate]) => <div className="team-row" key={name}><span><Avatar initials={initials} tone="slate" /><strong>{name}</strong></span><b>{active}</b><b className={due !== '0' ? 'due-count' : ''}>{due}</b><span className="completion"><i style={{ width: rate }} />{rate}</span></div>)}</div></section>
      </div>
    </main>
    {reportOpen && <ReportModal onClose={() => setReportOpen(false)} onSubmit={() => { setReportOpen(false); notify('Field report submitted to the action queue') }} />}
    {selected && <DetailDrawer violation={selected} onClose={() => setSelected(null)} onAction={() => { setSelected(null); notify(`Action assigned for ${selected.id}`) }} />}
    {toast && <div className="toast"><Check size={16} />{toast}</div>}
  </div>
}

function NavItem({ icon, label, active = false }: { icon: React.ReactNode; label: string; active?: boolean }) { return <button className={`nav-item ${active ? 'active' : ''}`} title={label}><span>{icon}</span><em>{label}</em></button> }
function ReportModal({ onClose, onSubmit }: { onClose: () => void; onSubmit: () => void }) { return <div className="overlay"><div className="modal"><div className="modal-header"><div><p className="eyebrow">NEW FIELD REPORT</p><h2>Quick field report</h2><p>Capture a safety observation from the field.</p></div><IconButton label="Close report form" onClick={onClose}><X /></IconButton></div><div className="form-grid"><label>Category<select><option>Roof &amp; ground control</option><option>PPE compliance</option><option>Haul-road safety</option></select></label><label>Severity<select><option>High</option><option>Critical</option><option>Medium</option><option>Low</option></select></label><label className="full-field">Observation<textarea placeholder="Describe what you observed..." /></label><label>Mine area<select><option>Active Panel 3</option><option>Haul Road</option><option>Workshop</option><option>Coal Yard</option></select></label><label>GPS coordinates<div className="input-state"><span>23.7957° N, 86.4304° E</span><small>GPS captured</small></div></label><label className="full-field">Evidence <div className="upload-box"><CloudUpload size={22} /><span>Drop a photo or choose a file</span><small>JPG, PNG up to 10MB</small></div></label></div><div className="timestamp"><Check size={15} /> Device timestamp captured · 05 Sep 2026, 09:42 IST <button>Use manual location</button></div><label className="toggle-row"><span><strong>Unsafe situation</strong><small>Notify manager immediately</small></span><input type="checkbox" defaultChecked /><i /></label><div className="modal-actions"><button className="secondary-btn" onClick={onClose}>Save draft</button><button className="primary-btn" onClick={onSubmit}>Submit report <ArrowUpRight size={15} /></button></div></div></div> }
function DetailDrawer({ violation, onClose, onAction }: { violation: Violation; onClose: () => void; onAction: () => void }) { return <div className="overlay drawer-overlay"><div className="drawer"><div className="drawer-top"><span className="eyebrow">VIOLATION DETAIL</span><IconButton label="Close violation detail" onClick={onClose}><X /></IconButton></div><div className="drawer-title"><SeverityIcon type={violation.icon} /><div><h2>{violation.title}</h2><p>{violation.id} · {violation.area}</p></div></div><div className="detail-pills"><span className="status status-open">{violation.status}</span><span className="pill-high">{violation.severity} risk</span><span className="sla-overdue">{violation.sla}</span></div><div className="detail-evidence">Evidence image preview<div><CloudUpload size={24} /><span>Roof support survey.jpg</span></div></div><div className="detail-facts"><span><small>Reported by</small><b>{violation.reporter}</b></span><span><small>GPS location</small><b>23.7957° N, 86.4304° E</b></span><span><small>OCR preview</small><b>“Spacing measured at 1.46m”</b></span></div><h3>Corrective-action checklist</h3><label className="check-row"><input type="checkbox" defaultChecked /> Isolate affected panel</label><label className="check-row"><input type="checkbox" /> Install additional roof supports</label><label className="check-row"><input type="checkbox" /> Upload verification photo</label><h3>Audit timeline</h3><div className="audit"><p><b>Report submitted</b><span>Today, 07:24 · Rakesh Singh</span></p><p><b>Manager notified</b><span>Today, 07:25 · Automated</span></p><p><b>Awaiting assignment</b><span>Today, 09:42 · MineOS</span></p></div><button className="primary-btn drawer-action" onClick={onAction}>Assign corrective action <ArrowUpRight size={15} /></button></div></div> }

export { NavItem, Avatar, ReportModal, DetailDrawer }
